[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "20.7"
apscheduler = "3.10.4"
python-dateutil = "2.8.2"
